### ISSUE TITLE
Don't put an actual function definition in a header file!

### ISSUE THREAD

**Issue by NerdOfCode** [NerdOfLinux/C#1]
Don't put the function definitions in the header file. Only put the function prototypes in the header file.

    Math/core.h

**Comment by NerdOfLinux** [comment]
This seems to be a much debated topic. While I did find many sources saying the same thing, I also found sources that [say otherwise](https://stackoverflow.com/a/21260826).

I want to call a handful of functions from many files. Having all the functions in one file seems easier than maintaining a separate version of each function in each file.

**Comment by NerdOfCode** [comment]
If you believe otherwise, I probably should stop wasting my time...
